### PR TITLE
Nano USB now faces North

### PR DESCRIPTION
**Pull request by FunDeckHermit**

### CODE REVIEW

**Comment by Lc9real** [comment]
I know thats maybe to much but could you move the arduino to the top like in my versionso that the cable doesnt go under the pcb

**Comment by FunDeckHermit** [comment]
I think that's an excellent exercise for you.

**Comment by Lc9real** [comment]
image
Is this good?

**Comment by FunDeckHermit** [comment]
I always try to point my GND's down and my power symbols (+5V) up.

**Comment by Lc9real** [comment]
image
like this?

**Comment by FunDeckHermit** [comment]
Almost, try not to intersect lines with symbols. Just place the GND to the left of of BRD1

**Comment by Lc9real** [comment]
image

**Comment by Lc9real** [comment]
image
is there a way to just delet all wires so i can wire it again and add a gnd plane

**Comment by Lc9real** [comment]
should i put the gnd zone on the top or bottom layer

**Comment by FunDeckHermit** [comment]
You can select "Tracks", then select all, then delete. 
For single tracks: select a track part, expand that to whole trace with "U", then delete.
Ground pour needs to be bottom and top.

**Comment by Lc9real** [comment]
image
this is waht i have

**Comment by FunDeckHermit** [comment]
Did you run the DRC? Tools -> Design Rule Checker?

**Comment by Lc9real** [comment]
image
image

**Comment by Lc9real** [comment]
i cant find drc

**Comment by Lc9real** [comment]
image

**Comment by FunDeckHermit** [comment]
It's under Inspect -> Design Rule Checker
Not under Tools, Sorry

**Comment by Lc9real** [comment]
image
image
this isnt a problem^
image
and this?^

**Comment by FunDeckHermit** [comment]
"this isnt a problem"
Then you shouldn't have connected that pad in the schematic. You can undo it in the schematic to fix it in the design. 

Silkscreen is the white layer for text and reference designators. 
image
I would move the RotaryEncoder1 designator to somewhere else. .

**Comment by Lc9real** [comment]
can i turn the mask off?

**Pull request merged**
